# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  # - name: Tour
  #   url: tour
  #   weight: 10
  - name: Home
    url: /
    weight: 30
  - name: People
    url: people
    weight: 40
  - name: Publications
    url: publication
    weight: 60
  - name: Reading Group
    url: reading-group
    weight: 40
  - name: Projects
    url: projects
    weight: 60
  # - name: Join us
  #   url: join
  #   weight: 60
